open-reaction-database/ord-app

ui/src/App.tsx
ui/src/common/styling/theme.ts

This PR includes an updated mantine theme in accordance with the current style guide in Figma

feat: Update mantine theme

---

ui/src/common/components/Pagination/Pagination.tsx
ui/src/common/utils/downloadFile.ts
ui/src/pages/dataset/DatasetPage/DatasetPage.module.scss
ui/src/pages/dataset/DatasetPage/DatasetPage.tsx
ui/src/pages/dataset/DatasetPage/DownloadMenu/DownloadMenu.module.scss
ui/src/pages/dataset/DatasetPage/DownloadMenu/DownloadMenu.tsx

This PR includes `DownloadMenu` component with options to download dataset in 3 different formats

Dataset download button

---

ui/src/common/components/UserMenu/UserMenu.tsx
ui/src/common/hooks/useAuth.ts
ui/src/core/AppRoot.tsx
ui/src/pages/ContributePage/GroupsSidebar/GroupsDrawer/AddMemberInput/AddMemberInput.tsx
ui/src/pages/ContributePage/GroupsSidebar/GroupsDrawer/GroupMembersList/GroupMembersList.module.scss
ui/src/pages/ContributePage/GroupsSidebar/GroupsDrawer/GroupMembersList/GroupMembersList.tsx
ui/src/pages/ContributePage/GroupsSidebar/GroupsDrawer/GroupMembersList/UserDataField/UserDataField.module.scss
ui/src/pages/ContributePage/GroupsSidebar/GroupsDrawer/GroupMembersList/UserDataField/UserDataField.tsx
ui/src/pages/ContributePage/GroupsSidebar/GroupsDrawer/PermissionModal/PermissionModal.tsx
ui/src/store/groups/groups.selectors.ts
ui/src/store/users/users.actions.ts
ui/src/store/users/users.reducer.ts
ui/src/store/users/users.selectors.ts
ui/src/store/users/users.thunks.ts
ui/src/store/users/users.types.ts

This PR includes:
- Display ORCID or 'Unavailable' where applicable
- Store the internal user instead of the Auth0 user
- Refactor code based on feedback from review #179

Group management enhancements

---

ui/src/common/components/ConfirmPopover/ConfirmPopover.module.scss
ui/src/common/components/ConfirmPopover/ConfirmPopover.tsx
ui/src/pages/ContributePage/GroupsSidebar/GroupsDrawer/RoleSelector/RoleSelector.tsx
ui/src/pages/DatasetPage/DatasetHeader/DatasetHeader.tsx
ui/src/pages/DatasetPage/DatasetHeader/datasetHeader.module.scss
ui/src/store/datasets/datasets.actions.ts
ui/src/store/datasets/datasets.thunks.ts

This PR includes:
- Dataset removal functionality
- `ConfirmPopover` component

Remove dataset UI

---

ui/src/common/components/FormModal/FormModal.tsx
ui/src/pages/ContributePage/DatasetTable/DatasetTable.tsx
ui/src/pages/ContributePage/DatasetTable/datasetTable.columns.tsx
ui/src/pages/ContributePage/DatasetTopActions/CreateDatasetFromFile/CreateDatasetFromFile.tsx
ui/src/pages/DatasetPage/DatasetHeader/DatasetHeader.tsx
ui/src/pages/DatasetPage/DatasetHeader/datasetHeader.module.scss
ui/src/pages/DatasetPage/ReactionList/CreateReactionMenu/CreateReactionFromFile/CreateReactionFromFile.tsx
ui/src/pages/ReactionPage/ReactionHeader/ReactionHeader.tsx
ui/src/store/reactions/reactions.reducer.ts
ui/src/store/reactions/reactions.selectors.ts

This PR includes various bug fixes related to the Contribute and Dataset pages

App bugfixes

---

ui/src/common/components/display/DataTable/DataTable.tsx

#297 
If data is empty change layout mode.

297: Update layout mode for DataTable

---

ui/src/features/groups/GroupsSidebar/GroupsDrawer/PermissionModal/PermissionModal.tsx

Issue => https://github.com/open-reaction-database/ord-app/issues/276
✅ Completed Task (According to Expected Behavior)

276 -  UI updates related to Roles & Permissions Table

---

ui/src/common/components/InputModal/InputModal.tsx
ui/src/features/datasets/CreateDatasetFromFile/CreateDatasetFromFile.tsx
ui/src/features/datasets/CreateDatasetFromFile/createDatasetFromFile.schema.ts
ui/src/features/datasets/CreateNewDataset/CreateNewDataset.tsx
ui/src/features/datasets/CreateNewDataset/createNewDataset.schema.ts
ui/src/features/datasets/DatasetHeader/EditDataset/EditDataset.tsx
ui/src/features/groups/GroupsSidebar/GroupsDrawer/GroupsDrawer.tsx
ui/src/features/reactions/ReactionHeader/ReactionHeader.tsx
ui/src/features/reactions/ReactionList/CreateReactionMenu/CreateReactionFromFile/CreateReactionFromFile.tsx
ui/src/features/reactions/ReactionList/CreateReactionMenu/CreateReactionMenu.tsx
ui/src/features/reactions/ReactionList/ReactionList.tsx
ui/src/features/reactions/ReactionList/reactionsList.module.scss
ui/src/pages/DatasetsList/DatasetsListTopActions/DatasetsListTopActions.tsx

Issue => https://github.com/open-reaction-database/ord-app/issues/173
1. Button name: "From File"; Description: "Create dataset from file"; Modal window button name: "Save";"Dataset file" description: ".binpb, .txtpb, .json "pipe symbol" Max: 100 MB"
2. "Dataset name"; "Save"
3. "Save as Template" 
4. No text, empty field as it is in Dataset Creation from Scratch modal window; "Cancel" 
5. - "Edit Reaction ID"; No text, empty field as it is in Dataset Creation from Scratch modal window; "Cancel"
6. Name of modal window: "Edit Group Name" "Close" button -> "Cancel" No placeholder if name field is empty It should be as for Edit Dataset modal window
7. Change the second option in dropdown to "From File" Modal name is changed to "Create Reaction from File" Placeholder "Attach file" in modal …

173 - Update text inconsistencies in different UI elements

---

ui/src/common/components/GroupsListWithRoles/GroupsListWithRoles.module.scss
ui/src/common/components/GroupsListWithRoles/GroupsListWithRoles.tsx
ui/src/common/components/display/Counter/counter.module.scss
ui/src/features/datasets/DatasetHeader/DatasetHeader.tsx
ui/src/features/datasets/DatasetTable/datasetTable.columns.tsx
ui/src/features/groups/GroupsList/GroupsList.module.scss
ui/src/features/groups/GroupsList/GroupsList.tsx
ui/src/index.scss
ui/src/store/entities/datasets/datasets.types.ts
ui/src/store/entities/groups/groups.types.ts

Feature: #150
- Added New component GroupsListWithRoles;
- Added selected state for groups in My Groups list;
- Updated Counter component to use Badge mantine inside.
https://github.com/user-attachments/assets/7142e56c-4e52-4e33-8379-dbfc1ddbbfec

150: Multiple groups view in Dataset table on Contribute page

---

ui/src/common/components/inputs/AppNumberInput/AppNumberInput.tsx
ui/src/common/components/inputs/ValuePrecisionUnitControl/ValuePrecisionUnitControl.tsx
ui/src/features/groups/GroupsList/GroupsList.module.scss
ui/src/features/groups/GroupsList/GroupsList.tsx
ui/src/features/reactions/ReactionHeader/ReactionHeader.tsx
ui/src/features/reactions/ReactionList/ReactionCard/ReactionCard.module.scss
ui/src/store/entities/reactions/reactionEntity/reactionEntity.converters.ts
ui/src/store/entities/reactions/reactions.actions.ts
ui/src/store/entities/reactions/reactions.reducer.ts
ui/src/store/entities/reactions/reactions.thunks.ts
ui/src/store/entities/reactions/reactions.types.ts

* Fixed delete reaction part thunk not updating reaction reducer
* Fixed group list item behavior on hover
* Fixed reaction title display for long items

Fixed extra fields being added to protobuf on load & save

---

ui/src/common/components/ReactionPreview/reactionPreview.module.scss
ui/src/features/datasets/CreateDatasetFromFile/createDatasetFromFile.schema.ts
ui/src/features/datasets/CreateNewDataset/createNewDataset.schema.ts
ui/src/features/enumeration/EnumerateButton.tsx
ui/src/features/enumeration/EnumerationSetup/EnumerationSetup.tsx
ui/src/features/enumeration/EnumerationWizard.tsx
ui/src/features/groups/GroupSelector/GroupSelector.tsx
ui/src/features/reactions/ReactionEntities/entityFormConfiguration/measurements/MeasurementMasses.tsx
ui/src/features/reactions/ReactionList/CreateReactionMenu/CreateReactionMenu.tsx
ui/src/features/templates/ImportFromJSON/ImportFromJSON.tsx
ui/src/features/templates/ImportFromJSON/importFromJson.schema.ts
ui/src/features/templates/TemplateHeader/TemplateHeader.tsx
ui/src/features/templates/TemplateHeaderActions/TemplateHeaderActions.tsx
ui/src/pages/TemplatesList/TemplatesList.page.tsx
ui/src/pages/TemplatesList/TemplatesTopActions/TemplatesTopActions.tsx
ui/src/store/configureAppStore.ts
ui/src/store/entities/enumeration/enumeration.thunks.ts
ui/src/store/entities/reactions/reactionEntity/reactionEntity.converters.ts
ui/src/store/entities/reactions/reactions.reducer.ts
ui/src/store/entities/templates/templates.actions.ts
ui/src/store/entities/templates/templates.reducer.ts
ui/src/store/entities/templates/templates.thunks.ts
ui/src/store/entities/templates/templates.types.ts
ui/src/store/features/enumerationWorker/worker.ts
ui/src/store/features/features.reducer.ts
ui/src/store/features/previewsWorker/previewsWorkerMiddleware.ts
ui/src/store/features/templateFromFileError/templateFromFileError.reducer.ts
ui/src/store/features/templateFromFileError/templateFromFileError.selectors.ts

Implemented enumeration entry points

---

ui/src/common/components/DownloadMenu/DownloadMenu.tsx

#382 
Add loader when downloading large datasets

382: Add loader when downloading large datasets

---

ui/src/features/groups/GroupSelector/GroupSelector.tsx
ui/src/features/reactions/ReactionEntities/entityFormConfiguration/reactionConditions.model.tsx
ui/src/store/entities/groups/groups.selectors.ts

Create dataset modal in groups field display only groups where user is admin or editor

---

ui/src/common/components/ReactionCard/ReactionCard.tsx
ui/src/common/components/ReactionCard/reactionCard.module.scss
ui/src/common/components/interactions/ConfirmPopover/ConfirmPopover.module.scss
ui/src/common/styling/colors.module.scss
ui/src/features/reactions/ReactionList/DatasetReactionCard/DatasetReactionCard.tsx
ui/src/features/reactions/ReactionList/reactionsList.module.scss

Marked invalid reactions via label

---

ui/src/common/components/inputs/FileControl/FileControl.tsx

https://github.com/user-attachments/assets/ea32d287-227a-4f02-b5a2-aa2b428775b7

475 - An empty file is generated if a Feature is created without attaching any files.

---

ui/src/features/reactions/ReactionEntities/ReactionTabs/ReactionContent.tsx
ui/src/pages/ReactionPage/ReactionPage.tsx
ui/src/pages/ReactionPage/reactionPage.module.scss
ui/src/store/entities/groups/groups.actions.ts
ui/src/store/entities/groups/groups.reducer.ts
ui/src/store/entities/groups/groups.thunks.ts
ui/src/store/features/groups/groups.reducer.ts

List view of all Reaction preview tabs for printing

---

ui/src/features/reactions/ReactionView/Inputs/InputsComponentsList/InputComponentsListItem/InputComponentsListItem.tsx

 450 - The component amount is shown without the ± value on the Structure pane and Input table.

---

ui/src/features/enumeration/EnumerationSetup/enumerationSetup.module.scss

500 - Long reaction name affects the "Create Dataset from Reaction Enumeration" sidebar.

---

ui/src/features/reactions/ReactionView/Conditions/Conditions.tsx
ui/src/features/reactions/ReactionView/Workups/Workups.tsx

 590 - Preview of Conditions and Workups

---

ui/src/common/dictionary/formatting.json
ui/src/features/datasets/DatasetTable/datasetTable.columns.tsx
ui/src/features/datasets/DatasetTable/datasetTable.module.scss
ui/src/features/groups/GroupsSidebar/GroupsDrawer/GroupMembersList/GroupMembersList.module.scss
ui/src/features/groups/GroupsSidebar/GroupsDrawer/GroupMembersList/GroupMembersList.tsx

357-Text formats for user e-mail and name

---

ui/src/features/reactions/ReactionView/Conditions/Conditions.tsx
ui/src/features/reactions/ReactionView/Workups/Workups.tsx

590- Preview of Conditions and Workups 
